In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1+cu102


In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
vector = torch.tensor([7,7])
vector.shape

torch.Size([2])

In [5]:
matrix = torch.tensor([[1,2],
                     [3,4],
                     [4,6]])
matrix.ndim

2

In [2]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [7]:
x = torch.arange(start=1, end=21)
print(x)

print(x.view(4, 5))

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20])
tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])
