In [14]:
import torch
import torch.nn as nn
import seaborn as sns
import matplotlib.pyplot as plt

In [15]:
x = torch.tensor([-1, 1, 2, 3], dtype=torch.float32)

In [16]:
# softmax
output = torch.softmax(x, dim=0)
print(output)
softmax = nn.Softmax(dim=0)
output = softmax(x)
print(output)

tensor([0.0120, 0.0889, 0.2418, 0.6572])
tensor([0.0120, 0.0889, 0.2418, 0.6572])


In [17]:
# sigmoid

output = torch.sigmoid(x)
print(output)
sigmoid = nn.Sigmoid()
output = sigmoid(x)
print(output)

tensor([0.2689, 0.7311, 0.8808, 0.9526])
tensor([0.2689, 0.7311, 0.8808, 0.9526])


In [18]:
# tanh
output = torch.tanh(x)
print(output)
tanh = nn.Tanh()
output = tanh(x)
print(output)

tensor([-0.7616,  0.7616,  0.9640,  0.9951])
tensor([-0.7616,  0.7616,  0.9640,  0.9951])


In [19]:
# relu
output = torch.relu(x)
print(output)
relu = nn.ReLU()
output = relu(x)
print(output)

tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.])


In [20]:
# leaky relu
output = torch.nn.functional.leaky_relu(x)
print(output)
leaky_relu = nn.LeakyReLU()
output = leaky_relu(x)
print(output)

tensor([-0.0100,  1.0000,  2.0000,  3.0000])
tensor([-0.0100,  1.0000,  2.0000,  3.0000])


In [21]:
# option 1(create nn Modules)
class NeuralNet1(nn.Module):
    def __init__(self, input_features, hidden_size):
        super(NeuralNet1, self).__init__()
        self.linear1 = nn.Linear(in_features=input_features, out_features=hidden_size)
        self.relu = nn.Relu()
        self.linear2 = nn.Linear(in_features=hidden_size, out_features=1)
        self.sigmoid = nn.Sigmoid()
    def forward(self):
        out = self.linear1(x)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out



In [23]:
# option 2 (use activation functions directly in forward pass)
class NeuralNet2(nn.Module):
    def __init__(self, in_features, hidden_size):
        super(self, NeuralNet2).__init__()
        self.linear1 = nn.Linear1(in_features=in_features, out_features=hidden_size)
        self.linear2 = nn.Linear2(in_features=hidden_size, out_features=1)
    def forward(self, x):
        out = torch.relu(self.linear1(x))
        out = torch.sigmoid(self.linear2(out))
        return out
